# Generated by Django 4.2.4 on 2023-08-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=5)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
