# Generated by Django 4.2.4 on 2023-09-01 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midnight_ace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('betting_round', models.CharField(max_length=20)),
                ('active_players', models.ManyToManyField(related_name='active_rounds', to='midnight_ace.player')),
                ('community_cards', models.ManyToManyField(to='midnight_ace.card')),
                ('winners', models.ManyToManyField(related_name='winning_rounds', to='midnight_ace.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pot', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('current_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_turn_for_game', to='midnight_ace.player')),
                ('deck', models.ManyToManyField(to='midnight_ace.card')),
                ('players', models.ManyToManyField(related_name='games_played', to='midnight_ace.player')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffled', models.BooleanField()),
                ('cards', models.ManyToManyField(related_name='decks_containing', to='midnight_ace.card')),
                ('drawn_cards', models.ManyToManyField(related_name='decks_drawn_from', to='midnight_ace.card')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bet_type', models.CharField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midnight_ace.player')),
            ],
        ),
    ]
